import { runMediaCommand } from "./ffmpeg";

// Precomputed waveform peaks in waveform-data JSON v2 format — exactly what
// peaks.js consumes via dataUri.json. Generated by streaming mono PCM out
// of ffmpeg and min/max-bucketing it incrementally, so a two-hour source
// never holds more than one chunk of samples in memory.

export const PEAKS_SAMPLE_RATE = 8000;
// 8000 / 400 = 20 waveform pixels per second of audio.
export const PEAKS_SAMPLES_PER_PIXEL = 400;

const INT16_BYTES = 2;
// Scale s16 samples down to the 8-bit range peaks.js renders.
const INT16_TO_INT8_DIVISOR = 256;

export interface WaveformJson {
  bits: 8;
  channels: 1;
  data: number[];
  length: number;
  sample_rate: number;
  samples_per_pixel: number;
}

// Incremental min/max reducer over little-endian s16 mono PCM. Chunks may
// split mid-sample; the dangling byte is carried into the next push.
export class PeaksAccumulator {
  private bucketMax = -32_768;
  private bucketMin = 32_767;
  private bucketFill = 0;
  private carry: Buffer | null = null;
  private readonly peaks: number[] = [];
  private readonly samplesPerPixel: number;

  constructor(samplesPerPixel = PEAKS_SAMPLES_PER_PIXEL) {
    this.samplesPerPixel = samplesPerPixel;
  }

  push(chunk: Buffer): void {
    const data = this.carry ? Buffer.concat([this.carry, chunk]) : chunk;
    const usableBytes = data.length - (data.length % INT16_BYTES);
    this.carry = usableBytes < data.length ? data.subarray(usableBytes) : null;

    for (let offset = 0; offset < usableBytes; offset += INT16_BYTES) {
      const sample = data.readInt16LE(offset);
      if (sample < this.bucketMin) {
        this.bucketMin = sample;
      }
      if (sample > this.bucketMax) {
        this.bucketMax = sample;
      }
      this.bucketFill += 1;
      if (this.bucketFill === this.samplesPerPixel) {
        this.flushBucket();
      }
    }
  }

  finish(): WaveformJson {
    if (this.bucketFill > 0) {
      this.flushBucket();
    }
    return {
      bits: 8,
      channels: 1,
      data: this.peaks,
      length: this.peaks.length / 2,
      sample_rate: PEAKS_SAMPLE_RATE,
      samples_per_pixel: this.samplesPerPixel,
    };
  }

  private flushBucket(): void {
    this.peaks.push(
      Math.floor(this.bucketMin / INT16_TO_INT8_DIVISOR),
      Math.floor(this.bucketMax / INT16_TO_INT8_DIVISOR)
    );
    this.bucketMin = 32_767;
    this.bucketMax = -32_768;
    this.bucketFill = 0;
  }
}

export async function generatePeaks(
  inputPath: string
): Promise<WaveformJson & { version: 2 }> {
  const accumulator = new PeaksAccumulator();

  await runMediaCommand(
    "ffmpeg",
    [
      "-v",
      "error",
      "-i",
      inputPath,
      "-f",
      "s16le",
      "-acodec",
      "pcm_s16le",
      "-ac",
      "1",
      "-ar",
      String(PEAKS_SAMPLE_RATE),
      "pipe:1",
    ],
    { onStdout: (chunk) => accumulator.push(chunk) }
  );

  return { version: 2, ...accumulator.finish() };
}
